version: '3.1'

services:
  nginx:
    build: ./nginx
    depends_on:
      - client
      - strapi
    ports:
      - "8080:8080"
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
  strapi:
    image: strapi/strapi:3.6.8
    volumes:
      - ./app:/srv/app
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1
    restart: always
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"